version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: test-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
