version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      bash -c "
      echo 'CREATE DATABASE IF NOT EXISTS testdb;' > /docker-entrypoint-initdb.d/init.sql;
      echo 'GRANT ALL PRIVILEGES ON testdb.* TO \"mysqluser\"@\"%\" IDENTIFIED BY \"mysqlpassword\";' >> /docker-entrypoint-initdb.d/init.sql;
      echo 'FLUSH PRIVILEGES;' >> /docker-entrypoint-initdb.d/init.sql;
      docker-entrypoint.sh mysqld
      "

volumes:
  mysql_data:
